blog/urls.py
from django.conf.urls import url

from blog.views import PostListView, PostDetailView, PostShareView

urlpatterns = [
    url(r'^$', PostListView.as_view(), name='post_list'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', PostListView.as_view(), name='post_list_by_tag'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', PostDetailView.as_view(),
        name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', PostShareView.as_view(), name='post_share'),
]

blog_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^jet/', include('jet.urls', namespace='jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', namespace='jet-dashboard')),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from taggit.managers import TaggableManager

from blog.constant import POST_STATUS_CHOICES, POST_CHOICE_DRAFT
from blog.managers import PostManager


class Post(models.Model):
    class Meta:
        ordering = ('-publish_date',)

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique_for_date='publish_date')
    author = models.ForeignKey(User, related_name='blog_posts')  # related_name nazwa odwrotnego zwiazku
    body = models.TextField()
    publish_date = models.DateTimeField(default=timezone.now)
    created_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=POST_STATUS_CHOICES, default=POST_CHOICE_DRAFT)
    tags = TaggableManager()

    object = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish_date.year, self.publish_date.strftime('%m'),
                                                 self.publish_date.strftime('%d'), self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Komentarz dodany przez {} dla posta {}'.format(self.name, self.post)

blog/forms.py
from django import forms

from blog.models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=64)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.views.generic.list import ListView
from taggit.models import Tag

from blog.constant import POST_CHOICE_PUBLISHED
from blog.forms import EmailPostForm, CommentForm
from blog.models import Post


class PostListView(ListView):
    model = Post
    template_name = 'blog/post/list.html'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        tag_slug = self.kwargs.get('tag_slug', None)
        context = super(PostListView, self).get_context_data(**kwargs)
        object_list = Post.object.all()
        tag = None
        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            object_list = object_list.filter(tags__in=[tag])
        paginator = Paginator(object_list, self.paginate_by)
        page = self.request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)

        context['tag'] = tag
        context['posts'] = posts
        context['page'] = page
        return context


class PostDetailView(View):
    model = Post
    template_name = 'blog/post/detail.html'

    def get(self, request, year, month, day, post):
        comments, post = self._get_selected_comments_and_post(day, month, post, year)
        comment_form = CommentForm()
        post_tags_ids = post.tags.values_list('id', flat=True)
        similar_posts = Post.object.filter(tags__in=post_tags_ids).exclude(id=post.id)
        similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish_date')[:4]
        return render(request, self.template_name, {'post': post, 'comments': comments, 'comment_form': comment_form,
                                                    'similar_posts': similar_posts})

    def post(self, request, year, month, day, post):
        comments, post = self._get_selected_comments_and_post(day, month, post, year)
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
        return render(request, self.template_name, {'post': post, 'comments': comments, 'comment_form': comment_form})

    @staticmethod
    def _get_selected_comments_and_post(day, month, post, year):
        post = get_object_or_404(Post, slug=post, status=POST_CHOICE_PUBLISHED, publish_date__year=year,
                                 publish_date__month=month, publish_date__day=day)
        comments = post.comments.filter(active=True)
        return comments, post


class PostShareView(View):
    model = Post
    template_name = 'blog/post/share.html'

    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id, status=POST_CHOICE_PUBLISHED)
        form = EmailPostForm()
        return render(request, self.template_name, {'post': post, 'form': form})

    def post(self, request, post_id):
        post = get_object_or_404(Post, id=post_id, status=POST_CHOICE_PUBLISHED)
        form = EmailPostForm(request.POST)
        sent = False
        if form.is_valid():
            email_data = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) zacheca do przeczytania "{}"'.format(email_data['name'], email_data['email'],
                                                                    post.title)
            message = 'Przeczytaj post "{}" na stronie {} \n\n Komentarz dodany przez {}: {}'.format(post.title,
            post_url, email_data['name'], email_data['comments'])
            send_mail(subject=subject, message=message, from_email='admin@myblock.com',
                                 recipient_list=[email_data['to']])
            sent = True
        return render(request, self.template_name, {'post': post, 'form': form, 'sent': sent})

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div id="sidebar">
    <h2>Mój blog</h2>
      <p>To jest mój blog.</p>
  </div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Opublikowany {{ post.publish }} przez {{ post.author }}
  </p>
  {{ post.body|linebreaks }}
  <p>
    <a href="{% url "blog:post_share" post.id %}">
      Udostępnij posta
    </a>
  </p>

  <h2>Podobne posty</h2>
  {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
  {% empty %}
    Nie ma podobnych postów.
  {% endfor %}

  {% with comments.count as total_comments %}
    <h2>
      {{ total_comments }} komentarz{{ total_comments|pluralize:"y" }}
    </h2>
  {% endwith %}

  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Komentarz {{ forloop.counter }} dodany przez {{ comment.name }}
          {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
  {% empty %}
    <p>Nie ma jeszcze żadnych komentarzy.</p>
  {% endfor %}

  {% if new_comment %}
    <h2>Twój komentarz został dodany.</h2>
  {% else %}
    <h2>Dodaj nowy komentarz</h2>
    <form action="." method="post">
      {{ comment_form.as_p }}
      {% csrf_token %}
      <p><input type="submit" value="Dodaj komentarz"></p>
    </form>
  {% endif %}
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}Mój blog{% endblock %}

{% block content %}
  <h1>Mój blog</h1>
  {% if tag %}
    <h2>Posty oznaczone tagiem "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="tags">
      Tagi:
      {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
    <p class="date">
      Opublikowany {{ post.publish }} przez {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}

  {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Udostępnij posta{% endblock %}

{% block content %}
  {% if sent %}
    <h1>Wiadomość e-mail została wysłana</h1>
    <p>
      "Wysłanie posta {{ post.title }}" do {{ cd.to }} zakończyło się sukcesem.
    </p>
  {% else %}
    <h1>Udostępnij "{{ post.title }}" przez e-mail</h1>
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Wyślij wiadomość e-mail">
    </form>
  {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Poprzednia</a>
    {% endif %}
    <span class="current">
      Strona {{ page.number }} z {{ page.paginator.num_pages }}.
    </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Następna</a>
      {% endif %}
  </span>
</div>